imports:
  - { resource: parameters.yml }
  - { resource: security.yml }
  - { resource: services.yml }
  - { resource: service_aliases.yml }

parameters:
  locale: en

framework:
  secret: "%secret%"
  router:
    resource: "%kernel.root_dir%/config/routing.yml"
    strict_requirements: ~
  form:            ~
  csrf_protection: ~
  validation:      { enable_annotations: true }
  templating:
    engines: ['twig']
  default_locale:  "%locale%"
  trusted_hosts:   ~
  trusted_proxies: ~
  session:
    handler_id:  session.handler.native_file
    save_path:   "%kernel.root_dir%/../var/sessions/%kernel.environment%"
  fragments:       ~
  http_method_override: true
  assets: ~
  php_errors:
    log: true

twig:
  debug:            "%kernel.debug%"
  strict_variables: "%kernel.debug%"

doctrine:
  dbal:
    driver:   "%database_driver%"
    host:     "%database_host%"
    port:     "%database_port%"
    dbname:   "%database_name%"
    user:     "%database_user%"
    password: "%database_password%"
    charset:  UTF8
    logging: false

  orm:
    auto_generate_proxy_classes: "%kernel.debug%"
    naming_strategy: doctrine.orm.naming_strategy.underscore
    auto_mapping: true

doctrine_migrations:
  dir_name: "%kernel.root_dir%/../src/Migration"
  namespace: Migration
  table_name: app_migrations
  name: App migrations

#Nelmio CORS Config
nelmio_cors:
  defaults:
    allow_credentials: false
    allow_origin: ['*']
    allow_headers: ['*']
    allow_methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS']
    max_age: 3600
    hosts: []
    origin_regex: false

#FOSRest Config
fos_rest:
  body_listener: true
  format_listener:
    rules:
      - { path: '^/', priorities: ['json'], fallback_format: json, prefer_extension: false }
  param_fetcher_listener: true
  view:
    view_response_listener: 'force'
    formats:
      json: true
  exception:
    enabled: true
